USE [master]
GO

/****** Object:  Database [DemoDB]    Script Date: 2015-05-08 21:30:24 ******/
CREATE DATABASE [DemoDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'DemoDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.SQLEXPRESS\MSSQL\DATA\DemoDB.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'DemoDB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.SQLEXPRESS\MSSQL\DATA\DemoDB_log.ldf' , SIZE = 2048KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [DemoDB] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [DemoDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [DemoDB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [DemoDB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [DemoDB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [DemoDB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [DemoDB] SET ARITHABORT OFF 
GO

ALTER DATABASE [DemoDB] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [DemoDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [DemoDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [DemoDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [DemoDB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [DemoDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [DemoDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [DemoDB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [DemoDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [DemoDB] SET  DISABLE_BROKER 
GO

ALTER DATABASE [DemoDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [DemoDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [DemoDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [DemoDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [DemoDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [DemoDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [DemoDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [DemoDB] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [DemoDB] SET  MULTI_USER 
GO

ALTER DATABASE [DemoDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [DemoDB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [DemoDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [DemoDB] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [DemoDB] SET  READ_WRITE 
GO


